services:
  - type: web
    name: Movie_Website
    runtime: node
    repo: https://github.com/contextCode/Movie_Website
    plan: free
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PORT
        sync: false
    region: frankfurt
    buildCommand: npm run build
    startCommand: npm run start
version: "1"
